
result_code = int

; It is easiest to treat error as its own message type
; (vs making all elements optional)
echo_error_rsp = {
    "rc" : (result_code),
}

echo_cmd  = {
    "d" : tstr
}

echo_rsp  = {
    "r" : tstr
}
